branches:
  only:
    - master
language: node_js
sudo: true
node_js:
  - stable
cache:
  directories:
    - node_modules
after_script:
    - npm run coveralls
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
